"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
from math import sqrt

from src.utils import timer


def is_pentagonal(p):
    # p = n(3n−1)/2 ->
    n = (1 + sqrt(1 + 24 * p)) / 6
    return n.is_integer()


def is_hexagonal(h):
    # h = n(2n−1) ->
    n = (1 + sqrt(1 + 8 * h)) / 4
    return n.is_integer()


@timer
def problem45():
    n = 286
    triangle = n * (n + 1) // 2
    while not is_pentagonal(triangle) or not is_hexagonal(triangle):
        n += 1
        triangle = n * (n + 1) // 2
    return triangle


if __name__ == "__main__":
    # 1533776805
    print(problem45())
